### ISSUE TITLE
Getting device log error when copy and pasting the login-page.js and login-page.xml from lesson 1

### ISSUE THREAD

**Issue by micahblu** [NativeScript/playground-tutorials#34]
In the playground as instructed I updated the "login-page.js" and "login-page.xml" files and hit save. 

This is my url: https://play.nativescript.org/?template=groceries-js&tutorial=groceries-js&autoStart=true&id=kWgCrz&v=7

Here is exactly what I have for each:

login-page.js
```js
var observableModule = require("tns-core-modules/data/observable");

function LoginViewModel() {
    var viewModel = observableModule.fromObject({

        favoriteFruits: [
            { type: "🍎", count: 7 },
            { type: "🍌", count: 15 },
            { type: "🍍", count: 12 },
            { type: "🍒", count: 30 },
            { type: "🍇", count: 16 }
        ]
    });

    return viewModel;
}

var loginViewModel = LoginViewModel();

function pageLoaded(args) {
    var page = args.object;
    page.bindingContext = loginViewModel;
}

exports.pageLoaded = pageLoaded;
```
login-page.xml
```xml
<Page loaded="pageLoaded" class="page" xmlns="http://www.nativescript.org/tns.xsd">
    <ActionBar title="Groceries"></ActionBar>
    <GridLayout rows="auto, *" xmlns:chart="nativescript-ui-chart" style="height: 1000px">
        <chart:RadCartesianChart id="cartesianChart" style="height: 100%">
            <chart:RadCartesianChart.series>
                <chart:BarSeries items="{{ favoriteFruits }}"
                    categoryProperty="type" valueProperty="count">
                    <chart:BarSeries.horizontalAxis>
                        <chart:CategoricalAxis />
                    </chart:BarSeries.horizontalAxis>
                    <chart:BarSeries.verticalAxis>
                        <chart:LinearAxis />
                    </chart:BarSeries.verticalAxis>
                </chart:BarSeries>
            </chart:RadCartesianChart.series>
        </chart:RadCartesianChart>
    </GridLayout>
</Page>
```

After I hit save I see this in my device and in the device logs:

[Galaxy S9]: An uncaught Exception occurred on "main" thread.
java.lang.RuntimeException: Unable to start activity ComponentInfo{org.nativescript.preview/com.tns.NativeScriptActivity}: com.tns.NativeScriptException: 
Calling js method onCreate failed

Error: Building UI from XML. @file:///app/app-root.xml:1:1
> com.tns.NativeScriptException: Failed to find module: "tns-core-modules/data/observables", relative to: app/tns_modules/
com.tns.Module.resolvePathHelper(Module.java:146)
com.tns.Module.resolvePath(Module.java:55)
com.tns.Runtime.callJSMethodNative(Native Method)
com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1120)
com.tns.Runtime.callJSMethodImpl(Runtime.java:1000)
com.tns.Runtime.callJSMethod(Runtime.java:987)
com.tns.Runtime.callJSMethod(Runtime.java:967)
com.tns.Runtime.callJSMethod(Runtime.java:959)
com.tns.NativeScriptActivity.onCreate(NativeScriptActivity.java:18)
android.app.Activity.performCreate(Activity.java:7183)
android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1220)
android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2908)
android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3030)
android.app.ActivityThread.-wrap11(Unknown Source:0)
android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696)
android.os.Handler.dispatchMessage(Handler.java:105)
android.os.Looper.loop(Looper.java:164)
android.app.ActivityThread.main(ActivityThread.java:6938)
java.lang.reflect.Method.invoke(Native Method)
com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
File: "file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/builder/builder.js, line: 244, column: 20

StackTrace: 
Frame: function:'ScopeError', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/utils/debug.js', line: 63, column: 24
Frame: function:'SourceError', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/utils/debug.js', line: 74, column: 23
Frame: function:'', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/builder/builder.js', line: 263, column: 17
Frame: function:'', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/builder/builder.js', line: 244, column: 33
Frame: function:'', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/xml/xml.js', line: 148, column: 13
Frame: function:'EasySAXParser.parse', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/js-libs/easysax/easysax.js', line: 751, column: 23
Frame: function:'XmlParser.parse', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/xml/xml.js', line: 195, column: 22
Frame: function:'XmlStringParser.parse', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/builder/builder.js', line: 250, column: 27
Frame: function:'parseInternal', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/builder/builder.js', line: 212, column: 11
Frame: function:'loadInternal', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/builder/builder.js', line: 117, column: 27
Frame: function:'loadPage', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/builder/builder.js', line: 53, column: 27
Frame: function:'', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/builder/builder.js', line: 72, column: 12
Frame: function:'', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/builder/builder.js', line: 86, column: 20
Frame: function:'ActivityCallbacksImplementation.setActivityContent', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/frame/frame.js', line: 899, column: 50
Frame: function:'ActivityCallbacksImplementation.onCreate', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/frame/frame.js', line: 751, column: 14
Frame: function:'NativeScriptActivity.onCreate', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/frame/activity.js', line: 20, column: 25

at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2955)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3030)
at android.app.ActivityThread.-wrap11(Unknown Source:0)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696)
at android.os.Handler.dispatchMessage(Handler.java:105)
at android.os.Looper.loop(Looper.java:164)
at android.app.ActivityThread.main(ActivityThread.java:6938)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
Caused by: com.tns.NativeScriptException: 
Calling js method onCreate failed

Error: Building UI from XML. @file:///app/app-root.xml:1:1
> com.tns.NativeScriptException: Failed to find module: "tns-core-modules/data/observables", relative to: app/tns_modules/
com.tns.Module.resolvePathHelper(Module.java:146)
com.tns.Module.resolvePath(Module.java:55)
com.tns.Runtime.callJSMethodNative(Native Method)
com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1120)
com.tns.Runtime.callJSMethodImpl(Runtime.java:1000)
com.tns.Runtime.callJSMethod(Runtime.java:987)
com.tns.Runtime.callJSMethod(Runtime.java:967)
com.tns.Runtime.callJSMethod(Runtime.java:959)
com.tns.NativeScriptActivity.onCreate(NativeScriptActivity.java:18)
android.app.Activity.performCreate(Activity.java:7183)
android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1220)
android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2908)
android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3030)
android.app.ActivityThread.-wrap11(Unknown Source:0)
android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696)
android.os.Handler.dispatchMessage(Handler.java:105)
android.os.Looper.loop(Looper.java:164)
android.app.ActivityThread.main(ActivityThread.java:6938)
java.lang.reflect.Method.invoke(Native Method)
com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
File: "file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/builder/builder.js, line: 244, column: 20

StackTrace: 
Frame: function:'ScopeError', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/utils/debug.js', line: 63, column: 24
Frame: function:'SourceError', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/utils/debug.js', line: 74, column: 23
Frame: function:'', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/builder/builder.js', line: 263, column: 17
Frame: function:'', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/builder/builder.js', line: 244, column: 33
Frame: function:'', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/xml/xml.js', line: 148, column: 13
Frame: function:'EasySAXParser.parse', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/js-libs/easysax/easysax.js', line: 751, column: 23
Frame: function:'XmlParser.parse', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/xml/xml.js', line: 195, column: 22
Frame: function:'XmlStringParser.parse', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/builder/builder.js', line: 250, column: 27
Frame: function:'parseInternal', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/builder/builder.js', line: 212, column: 11
Frame: function:'loadInternal', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/builder/builder.js', line: 117, column: 27
Frame: function:'loadPage', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/builder/builder.js', line: 53, column: 27
Frame: function:'', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/builder/builder.js', line: 72, column: 12
Frame: function:'', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/builder/builder.js', line: 86, column: 20
Frame: function:'ActivityCallbacksImplementation.setActivityContent', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/frame/frame.js', line: 899, column: 50
Frame: function:'ActivityCallbacksImplementation.onCreate', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/frame/frame.js', line: 751, column: 14
Frame: function:'NativeScriptActivity.onCreate', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/frame/activity.js', line: 20, column: 25

at com.tns.Runtime.callJSMethodNative(Native Method)
at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1120)
at com.tns.Runtime.callJSMethodImpl(Runtime.java:1000)
at com.tns.Runtime.callJSMethod(Runtime.java:987)
at com.tns.Runtime.callJSMethod(Runtime.java:967)
at com.tns.Runtime.callJSMethod(Runtime.java:959)
at com.tns.NativeScriptActivity.onCreate(NativeScriptActivity.java:18)
at android.app.Activity.performCreate(Activity.java:7183)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1220)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2908)
... 9 more
[Galaxy S9]: An uncaught Exception occurred on "main" thread.
java.lang.RuntimeException: Unable to start activity ComponentInfo{org.nativescript.preview/com.tns.NativeScriptActivity}: com.tns.NativeScriptException: 
Calling js method onCreate failed

Error: Building UI from XML. @file:///app/app-root.xml:1:1
> com.tns.NativeScriptException: Failed to find module: "tns-core-modules/data/observables", relative to: app/tns_modules/
com.tns.Module.resolvePathHelper(Module.java:146)
com.tns.Module.resolvePath(Module.java:55)
com.tns.Runtime.callJSMethodNative(Native Method)
com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1120)
com.tns.Runtime.callJSMethodImpl(Runtime.java:1000)
com.tns.Runtime.callJSMethod(Runtime.java:987)
com.tns.Runtime.callJSMethod(Runtime.java:967)
com.tns.Runtime.callJSMethod(Runtime.java:959)
com.tns.NativeScriptActivity.onCreate(NativeScriptActivity.java:18)
android.app.Activity.performCreate(Activity.java:7183)
android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1220)
android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2908)
android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3030)
android.app.ActivityThread.-wrap11(Unknown Source:0)
android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696)
android.os.Handler.dispatchMessage(Handler.java:105)
android.os.Looper.loop(Looper.java:164)
android.app.ActivityThread.main(ActivityThread.java:6938)
java.lang.reflect.Method.invoke(Native Method)
com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
File: "file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/builder/builder.js, line: 244, column: 20

StackTrace: 
Frame: function:'ScopeError', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/utils/debug.js', line: 63, column: 24
Frame: function:'SourceError', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/utils/debug.js', line: 74, column: 23
Frame: function:'', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/builder/builder.js', line: 263, column: 17
Frame: function:'', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/builder/builder.js', line: 244, column: 33
Frame: function:'', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/xml/xml.js', line: 148, column: 13
Frame: function:'EasySAXParser.parse', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/js-libs/easysax/easysax.js', line: 751, column: 23
Frame: function:'XmlParser.parse', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/xml/xml.js', line: 195, column: 22
Frame: function:'XmlStringParser.parse', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/builder/builder.js', line: 250, column: 27
Frame: function:'parseInternal', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/builder/builder.js', line: 212, column: 11
Frame: function:'loadInternal', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/builder/builder.js', line: 117, column: 27
Frame: function:'loadPage', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/builder/builder.js', line: 53, column: 27
Frame: function:'', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/builder/builder.js', line: 72, column: 12
Frame: function:'', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/builder/builder.js', line: 86, column: 20
Frame: function:'ActivityCallbacksImplementation.setActivityContent', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/frame/frame.js', line: 899, column: 50
Frame: function:'ActivityCallbacksImplementation.onCreate', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/frame/frame.js', line: 751, column: 14
Frame: function:'NativeScriptActivity.onCreate', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/frame/activity.js', line: 20, column: 25

at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2955)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3030)
at android.app.ActivityThread.-wrap11(Unknown Source:0)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696)
at android.os.Handler.dispatchMessage(Handler.java:105)
at android.os.Looper.loop(Looper.java:164)
at android.app.ActivityThread.main(ActivityThread.java:6938)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
Caused by: com.tns.NativeScriptException: 
Calling js method onCreate failed

Error: Building UI from XML. @file:///app/app-root.xml:1:1
> com.tns.NativeScriptException: Failed to find module: "tns-core-modules/data/observables", relative to: app/tns_modules/
com.tns.Module.resolvePathHelper(Module.java:146)
com.tns.Module.resolvePath(Module.java:55)
com.tns.Runtime.callJSMethodNative(Native Method)
com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1120)
com.tns.Runtime.callJSMethodImpl(Runtime.java:1000)
com.tns.Runtime.callJSMethod(Runtime.java:987)
com.tns.Runtime.callJSMethod(Runtime.java:967)
com.tns.Runtime.callJSMethod(Runtime.java:959)
com.tns.NativeScriptActivity.onCreate(NativeScriptActivity.java:18)
android.app.Activity.performCreate(Activity.java:7183)
android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1220)
android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2908)
android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3030)
android.app.ActivityThread.-wrap11(Unknown Source:0)
android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696)
android.os.Handler.dispatchMessage(Handler.java:105)
android.os.Looper.loop(Looper.java:164)
android.app.ActivityThread.main(ActivityThread.java:6938)
java.lang.reflect.Method.invoke(Native Method)
com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
File: "file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/builder/builder.js, line: 244, column: 20

StackTrace: 
Frame: function:'ScopeError', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/utils/debug.js', line: 63, column: 24
Frame: function:'SourceError', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/utils/debug.js', line: 74, column: 23
Frame: function:'', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/builder/builder.js', line: 263, column: 17
Frame: function:'', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/builder/builder.js', line: 244, column: 33
Frame: function:'', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/xml/xml.js', line: 148, column: 13
Frame: function:'EasySAXParser.parse', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/js-libs/easysax/easysax.js', line: 751, column: 23
Frame: function:'XmlParser.parse', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/xml/xml.js', line: 195, column: 22
Frame: function:'XmlStringParser.parse', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/builder/builder.js', line: 250, column: 27
Frame: function:'parseInternal', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/builder/builder.js', line: 212, column: 11
Frame: function:'loadInternal', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/builder/builder.js', line: 117, column: 27
Frame: function:'loadPage', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/builder/builder.js', line: 53, column: 27
Frame: function:'', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/builder/builder.js', line: 72, column: 12
Frame: function:'', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/builder/builder.js', line: 86, column: 20
Frame: function:'ActivityCallbacksImplementation.setActivityContent', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/frame/frame.js', line: 899, column: 50
Frame: function:'ActivityCallbacksImplementation.onCreate', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/frame/frame.js', line: 751, column: 14
Frame: function:'NativeScriptActivity.onCreate', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/frame/activity.js', line: 20, column: 25

at com.tns.Runtime.callJSMethodNative(Native Method)
at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1120)
at com.tns.Runtime.callJSMethodImpl(Runtime.java:1000)
at com.tns.Runtime.callJSMethod(Runtime.java:987)
at com.tns.Runtime.callJSMethod(Runtime.java:967)
at com.tns.Runtime.callJSMethod(Runtime.java:959)
at com.tns.NativeScriptActivity.onCreate(NativeScriptActivity.java:18)
at android.app.Activity.performCreate(Activity.java:7183)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1220)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2908)
... 9 more

**Comment by mlars84** [comment]
Did you ever figure this out? Running into the same issue myself.
